version: 2

############################################################################

references:
   default_environment_settings: &default_environment_settings
      docker:
        - image: circleci/openjdk:8-node
     
############################################################################

jobs:
  build:
    <<: *default_environment_settings
    steps:
      - checkout
      - run:
          name: Install ant-contrib
          command: docker build -t zmimage .
############################################################################

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
############################################################################
