version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: ubuntu:18.04
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: 
         apt-get update
      - run: 
         apt-get install docker.io
      - run: 
         docker build -t image .

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
