version: 2

jobs:
  build:
   docker:
        - image: circleci/openjdk:8-node
    steps:
      - checkout
      - run:
          name: Install ant-contrib
          command: docker build -t zmimage .

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
